// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcgqqvfdjpslgxbuhwnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjZ3FxdmZkanBzbGd4YnVod25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDU1NzEsImV4cCI6MjA2NjAyMTU3MX0.kbgdxXQAfFzFWjPl4BQXBkfDV7BF0rWpFMwsupJY48U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);